### ISSUE TITLE
Issue#1 - diffGitHub_push.m Line 59 - remove call to origin.

### ISSUE THREAD

**Issue by smuckati1** [mathworks/Simulink-Model-Comparison-for-GitHub-Pull-Requests#1]
Hello,

Within diffGitHub_push.m on line 59, the git command currently says:
`gitCommand = sprintf('git show refs/remotes/origin/main %s:%s > %s', lastpush, fileName, ancestor);`

This means that in the git show command, we are calling to refs/remotes/origin/main AND "lastpush"

The correct command should be 
`gitCommand = sprintf('git show %s:%s > %s', lastpush, fileName, ancestor);`

Without this correction, this seems to lead to a failure in the git copy being properly created in R2023a, resulting in the visdiff operation failing. 

Can we please make this correction to line 59?

**Comment by rnakhoul** [comment]
Thank you for reporting. Fix in place!
