### ISSUE TITLE
Setup a display server instead of xvfb-run

### ISSUE THREAD

**Issue by acampbel** [mathworks/Simulink-Model-Comparison-for-GitHub-Pull-Requests#2]
If you enable a prior step to start a display server instead of using xvfb-run, the you can still highlight the matlab-actions/run-command action, which will work on both self hosted and GitHub hosted runners. Something like:

      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

**Comment by rnakhoul** [comment]
Addressed in https://github.com/mathworks/Simulink-Model-Comparison-for-GitHub-Pull-Requests/commit/9aac6232a608343e7b75a29c63c6c431ccc6c4e3
