### ISSUE TITLE
Show this on a GitHub hosted runner

### ISSUE THREAD

**Issue by acampbel** [mathworks/Simulink-Model-Comparison-for-GitHub-Pull-Requests#3]
Leveraging on a self hosted runner is great, but this can likely also work on a GitHub hosted runner. Perhaps add your own .github/workflows file which shows in action on this repo on a GitHub hosted runner.

**Comment by rnakhoul** [comment]
Addressed in https://github.com/mathworks/Simulink-Model-Comparison-for-GitHub-Pull-Requests/commit/9aac6232a608343e7b75a29c63c6c431ccc6c4e3
